using System.Data;
using BamboeUp.Report.Abstractions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BamboeUp.Report.QuestPdf.Rendering;

public static class DocPdfRenderer
{
    public static byte[] Render(ReportRunContext context, DataTable data)
    {
        if (data.Rows.Count == 0)
            throw new InvalidOperationException("No data returned for document print.");

        var row = data.Rows[0];
        var key = (context.DefinitionKey ?? string.Empty).Trim();

        return key switch
        {
            "BankMasterSlip" or "BankMasterSlip_QuestPDF" => RenderBankMasterSlip(context, row, "QuestPDF"),
            "BankConfirmationLetter" => RenderBankConfirmationLetter(context, row),
            _ when key.StartsWith("BankMasterSlip_", StringComparison.OrdinalIgnoreCase)
                => RenderBankMasterSlip(context, row, key["BankMasterSlip_".Length..]),
            _ => RenderGenericSlip(context, row)
        };
    }

    private static byte[] RenderBankMasterSlip(ReportRunContext context, DataRow row, string engineLabel)
    {
        var bankName = GetString(row, "BankName");
        var bankInitial = GetString(row, "BankInitial");
        var bankId = GetString(row, "BankId");
        var printedAt = GetDateString(row, "PrintedAt");

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(36);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text($"Bank Master Slip — {engineLabel}").Bold().FontSize(18).FontColor(Colors.Teal.Darken2);
                    col.Item().PaddingTop(4).Text(context.ProgramName).FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(2).Text($"Engine: {engineLabel}").FontSize(9).FontColor(Colors.Blue.Darken1);
                });

                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().PaddingBottom(8).Text("Bank Information").SemiBold().FontSize(13);
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(110);
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Bank ID", bankId);
                        AddRow(table, "Bank Name", bankName);
                        AddRow(table, "Initial", bankInitial);
                        AddRow(table, "Printed At", printedAt);
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by BamboeUp — ").FontSize(9).FontColor(Colors.Grey.Medium);
                    text.Span(context.ProgramCode).FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }

    private static byte[] RenderBankConfirmationLetter(ReportRunContext context, DataRow row)
    {
        var bankName = GetString(row, "BankName");
        var bankInitial = GetString(row, "BankInitial");
        var printId = context.Print.ReportPrintIdMasked ?? context.Print.ReportPrintId ?? string.Empty;
        var printedAt = GetDateString(row, "PrintedAt");

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(48);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().AlignCenter().Text("BANK CONFIRMATION LETTER").Bold().FontSize(16);
                    col.Item().PaddingTop(6).AlignCenter().Text(printedAt).FontSize(10).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(24).Column(col =>
                {
                    col.Item().Text("To Whom It May Concern,").LineHeight(1.4f);
                    col.Item().PaddingTop(16).Text(text =>
                    {
                        text.Span("This letter confirms that ").LineHeight(1.5f);
                        text.Span(bankName).SemiBold();
                        text.Span($" ({bankInitial}) is registered as an active bank master record in our system.");
                    });
                    col.Item().PaddingTop(16).Text("This document is issued for internal reference and confirmation purposes only.")
                        .LineHeight(1.5f).FontColor(Colors.Grey.Darken2);
                });

                page.Footer().Column(col =>
                {
                    if (!string.IsNullOrWhiteSpace(printId))
                        col.Item().AlignRight().Text($"Print ID: {printId}").FontSize(9).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(4).AlignCenter().Text($"{context.ProgramName} ({context.ProgramCode})")
                        .FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }

    private static byte[] RenderGenericSlip(ReportRunContext context, DataRow row)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.Header().Text(context.ProgramName).Bold().FontSize(16);
                page.Content().PaddingVertical(16).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(140);
                        columns.RelativeColumn();
                    });

                    foreach (DataColumn column in row.Table.Columns)
                        AddRow(table, column.ColumnName, row[column]?.ToString() ?? "-");
                });
            });
        }).GeneratePdf();
    }

    private static void AddRow(TableDescriptor table, string label, string? value)
    {
        table.Cell().PaddingVertical(4).Text(label).SemiBold();
        table.Cell().PaddingVertical(4).Text(string.IsNullOrWhiteSpace(value) ? "-" : value);
    }

    private static string GetString(DataRow row, params string[] columnNames)
    {
        foreach (var name in columnNames)
        {
            if (!row.Table.Columns.Contains(name))
                continue;
            var value = row[name]?.ToString();
            if (!string.IsNullOrWhiteSpace(value))
                return value;
        }
        return "-";
    }

    private static string GetDateString(DataRow row, string columnName)
    {
        if (!row.Table.Columns.Contains(columnName))
            return DateTime.Now.ToString("dd MMM yyyy HH:mm");

        var value = row[columnName];
        return value switch
        {
            DateTime dt => dt.ToString("dd MMM yyyy HH:mm"),
            DateTimeOffset dto => dto.ToString("dd MMM yyyy HH:mm"),
            _ => value?.ToString() ?? DateTime.Now.ToString("dd MMM yyyy HH:mm")
        };
    }
}
